---
# Source: flaskChart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "flask-svc"
spec:
  selector:
    app.kubernetes.io/name: flaskChart
    app.kubernetes.io/instance: flask-k8s
  ports:
  - name: "http"
    port: 5001
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
---
# Source: flaskChart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # i wanna use the release name
  name: flask-k8s
  labels:
    helm.sh/chart: flaskChart-0.1.0
    app.kubernetes.io/name: flaskChart
    app.kubernetes.io/instance: flask-k8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flaskChart
      app.kubernetes.io/instance: flask-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaskChart
        app.kubernetes.io/instance: flask-k8s
    spec:
      containers:
      - name: flaskweb
        image: "bopgeek/flask-web:v1"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
